<?php

/**
 * @file
 * Contains events.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\events\Services\EventServiceClass;
use Symfony\Component\HttpFoundation\Response;

function events_theme($existing, $type, $theme, $path) {
    return [
            'article_list' => [
                'variables' => [
                    'date' => [],
                    'tags' => '',
                    'context' => [],
                    'theme' => '',
                    'cache' => [],
                    'list' => [],
                ],
            ],
            'search_nodes' => [
                'variables' => [
                    'result' => [],
                ],
            ],
            'comments' => [
                'variables' => [
                    'comments' => [],
                    'subject' => [],
                    'body' => [],
                    'created' => [],
                 ]
            ],
        ];
}


