<?php

/**
 * @file
 * Contains events.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\events\Services\EventServiceClass;
use Symfony\Component\HttpFoundation\Response;

function events_theme($existing, $type, $theme, $path) {
    return [
            'article_list' => [
                'variables' => [
                    'date' => [],
                    'tags' => '',
                    'context' => [],
                    'theme' => '',
                    'cache' => [],
                    'list' => [],
                ],
            ],
            'search_nodes' => [
                'variables' => [
                    'result' => [],
                ],
            ],
            'comments' => [
                'variables' => [
                    'comments' => [],
                    'subject' => [],
                    'body' => [],
                    'created' => [],
                 ]
            ],
        ];
}

function events_preprocess_breadcrumb(&$variables) {
    $request = \Drupal::request();
    if ($route = $request->attributes->get(\Symfony\Cmf\Component\Routing\RouteObjectInterface::ROUTE_OBJECT)) {
        $title = \Drupal::service('title_resolver')->getTitle($request, $route);
    }
    if ($variables['breadcrumb']) {
        $variables['breadcrumb'][] = [
            'text' => $title
        ];
        $variables['#cache']['contexts'][] = 'url.path';
    }
}

