<?php

/**
 * @file
 * Contains events.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\events\Services\EventServiceClass;
use Symfony\Component\HttpFoundation\Response;

function events_theme($existing, $type, $theme, $path) {
    return [
        'article_list' => [
            'variables' => [
                'date' => [],
//                'path' => drupal_get_path('module', 'events') . '/templates',
                'tags' => '',
                'context' => [],
                'theme' => '',
                'cache' => [],
                'list' => [],
            ]
        ],
    ];
}

//function events_preprocess_html() {
//    $response = Response::create($json);
//    $response->headers->set('Cache-Control', 'max-age=150');
//    return $response;
//}

